-dontwarn okio.Okio # uses java.nio.*
-dontwarn okio.DeflaterSink # uses some random class
-dontwarn com.squareup.picasso.OkHttp3Downloader # uses okhttp3.**
-dontwarn com.squareup.picasso.OkHttpDownloader # uses com.squareup.okhttp.**
-dontwarn com.firebase.client.utilities.HttpUtilities # uses org.apache.http.**
-dontwarn com.firebase.client.authentication.* # uses org.apache.http.**
-dontwarn com.fasterxml.jackson.databind.ext.DOMSerializer # uses org.w3c.dom.bootstrap.DOMImplementationRegistry
