name: "CI"
on:
  push

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:

  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@cb91b4b05800bd3de29bc0e63900f304a45fbf06 # v3
    permissions:
      contents: read
      security-events: write
      actions: read


  build:
    name: "🔨 Build & Verify"
    needs: validate
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-24.04
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v5

      - name: "Set up JDK."
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: '.java-version'

      - name: "Set up Gradle."
        uses: gradle/actions/setup-gradle@v5

      - name: "Build & Verify project using Gradle."
        id: gradle
        shell: bash
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint

      - name: "Upload 'Reports' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Reports'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build/reports/

      - name: "Upload 'APKs' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'APKs'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/build/outputs/apk/


  shadow-build-agp:
    name: "🔮 Shadow Build / AGP"
    needs: validate
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-24.04
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v5

      - name: "Set up JDK."
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: '.java-version'

      - name: "Set up Gradle."
        uses: gradle/actions/setup-gradle@v5

      - name: "Build & Verify project using Gradle."
        id: gradle
        shell: bash
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint
          -Pcom.bumptech.glide.build.shadow=gradle/shadow-agp.versions.toml


  shadow-build-glide3-snapshot:
    name: "🔮 Shadow Build / Glide 3 SNAPSHOT"
    needs: validate
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-24.04
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v5

      - name: "Set up JDK."
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: '.java-version'

      - name: "Set up Gradle."
        uses: gradle/actions/setup-gradle@v5

      - name: "Build & Verify project using Gradle."
        id: gradle
        shell: bash
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint
          -Pcom.bumptech.glide.build.shadow=gradle/shadow-glide3-snapshot.versions.toml


  shadow-build-glide5-snapshot:
    name: "🔮 Shadow Build / Glide 5 SNAPSHOT"
    needs: validate
    timeout-minutes: 10

    permissions:
      # actions/checkout
      contents: read

    runs-on: ubuntu-24.04
    steps:

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v5

      - name: "Set up JDK."
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version-file: '.java-version'

      - name: "Set up Gradle."
        uses: gradle/actions/setup-gradle@v5

      - name: "Build & Verify project using Gradle."
        id: gradle
        shell: bash
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint
          -Pcom.bumptech.glide.build.shadow=gradle/shadow-glide5-snapshot.versions.toml
