name: CI
on:
  push
concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:

  validate:
    name: "🦺 Validation"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      # actions/checkout
      contents: read
    steps:
      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Validate Gradle Wrapper JARs."
        uses: gradle/wrapper-validation-action@v1


  build:
    name: "🔨 Build & Verify"
    needs: validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Build & Verify project using Gradle."
        id: gradle
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint

      - name: "Upload 'Reports' artifact."
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'Reports'
          path: |
            ${{ github.workspace }}/build/reports/

      - name: "Upload 'APKs' artifact."
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: 'APKs'
          path: |
            ${{ github.workspace }}/build/outputs/apk/


  shadow-build-agp:
    name: "🔮 Shadow Build / AGP"
    needs: validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Build & Verify project using Gradle."
        id: gradle
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint
          -Pcom.bumptech.glide.build.shadow=gradle/shadow-agp.versions.toml


  shadow-build-glide3-snapshot:
    name: "🔮 Shadow Build / Glide 3 SNAPSHOT"
    needs: validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Build & Verify project using Gradle."
        id: gradle
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint
          -Pcom.bumptech.glide.build.shadow=gradle/shadow-glide3-snapshot.versions.toml


  shadow-build-glide5-snapshot:
    name: "🔮 Shadow Build / Glide 5 SNAPSHOT"
    needs: validate
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Set up JDK 17."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Checkout ${{ github.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4

      - name: "Build & Verify project using Gradle."
        id: gradle
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          lint
          -Pcom.bumptech.glide.build.shadow=gradle/shadow-glide5-snapshot.versions.toml
